export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_MOVIES_SUCCESS= "GET_MOVIES_SUCCESS";
export const ADD_FAVORY= "ADD_FAVORY";
export const REMOVE_FAVORY= "REMOVE_FAVORY";
export const GET_MOVIE_DETAILS_SUCCESS="GET_MOVIE_DETAILS_SUCCESS";

